.\" myc.1	01/12/1996
.\"
.\" Copyright (c) 1995,1996 Sascha Demetrio
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\"    If you modify any part of HEXER and redistribute it, you must add
.\"    a notice to the `README' file and the modified source files containing
.\"    information about the  changes you made.  I do not want to take
.\"    credit or be blamed for your modifications.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"    If you modify any part of HEXER and redistribute it in binary form,
.\"    you must supply a `README' file containing information about the
.\"    changes you made.
.\" 3. The name of the developer may not be used to endorse or promote
.\"    products derived from this software without specific prior written
.\"    permission.
.\"
.\" HEXER WAS DEVELOPED BY SASCHA DEMETRIO.
.\" THIS SOFTWARE SHOULD NOT BE CONSIDERED TO BE A COMMERCIAL PRODUCT.
.\" THE DEVELOPER URGES THAT USERS WHO REQUIRE A COMMERCIAL PRODUCT
.\" NOT MAKE USE OF THIS WORK.
.\"
.\" DISCLAIMER:
.\" THIS SOFTWARE IS PROVIDED BY THE DEVELOPER ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE DEVELOPER BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\" 
.TH MYC 1 "1996 February 11" "Myc"
.\"
.\" --- Section -- NAME -------------------------------------------------------
.\"
.SH NAME
myc \- a simple calculator
.\"
.\" --- Section -- SYNOPSIS ---------------------------------------------------
.\"
.SH SYNOPSIS
.B myc
[command]
.\"
.\" --- Section -- DESCRIPTION ------------------------------------------------
.\"
.SH DESCRIPTION
.B Myc
is a simple calculator capable of all operations available in C.
Commands are entered in infix notation.  It is possible to use parentheses.
If a
.BR myc -command
is specified on the command-line, the result is echoed and
.B myc
exits immediately.
If invoked with no arguments,
.B myc
starts reading commands from standard-in.
.B myc
understands the following binary infix operators (from highest priority to
lowest):
.B **
(power),
.B *
(multiply),
.B /
(divide),
.B %
(modulo),
.B +
(add),
.B -
(subtract),
.B <<
(shift left),
.B >>
(shift right),
.B <
(less),
.B <=
(less or equal),
.B >
(greater),
.B >=
(greater or equal),
.B ==
(equal),
.B !=
(not equal),
.B &
(arithmetical and),
.B |
(arithmetical or),
.B ^
(arithmetical exclusive or),
.B &&
(logical and),
.B ||
(logical or),
.B =
(assign);  and the following unary prefix operators:
.B -
(negate, unary minus),
.B !
(logical not),
.B ~
(bitwise complement).
.B myc
knows three data types:
.BR boolean ,
.B integer
(32 bit),
.B float
(64 bit, equivalent to C double).
On some esoteric platforms the precision of integer and float may be
different.
As in C the result of a division depends on the data types of the operands.
An integer divided by an integer yields an integer.
If you want the result to be a float, make sure one of the operands is a
float, e.g. type
.I 4/7.
instead of
.I 4/7
or
.I a/(b+0.)
instead of
.IR a/b .
The power operation returns a float if the result is too large to fit in an
integer.
The result of a calculation is stored in the special variables
.B $$
and
.BI $ n
where
.I n
is the number of the command.
.\"
.\" --- Section -- BUGS -------------------------------------------------------
.\"
.SH BUGS
Maybe.  Please report bugs to
.IR demetrio@cs.uni-sb.de .
.\"
.\" --- Section -- COPYRIGHT --------------------------------------------------
.\"
.SH COPYRIGHT
.B myc
is
.BR "not in the public domain" ,
but freely distributable.  It may be used for any non-commercial purpose.
See file
.B COPYRIGHT
for details.
.\"
.\" --- Section -- AUTHOR -----------------------------------------------------
.\"
.SH AUTHOR
Sascha Demetrio
.br
.I demetrio@cs.uni-sb.de

